### ISSUE TITLE
Unable to enter administrator password on the new popup prompt after selecting flash “balenaEtcher wants to make changes.”

### ISSUE THREAD

**Issue by Decrypt0r** [balena-io/etcher#2997]
- **Etcher version: 1.5.66** 
- **Operating system and architecture: MacOS Catalina** 
- **Image flashed: Hypriot Docker** 
- **Do you see any meaningful error information in the DevTools? Console tab. No** 

Works on Administrator account, not on standard user account.

**Comment by thundron** [comment]
Hi, can you please describe a bit more the issue? Do you mean that you can't actually write the password (as in, you write but nothing happens) or that you can't confirm after writing the password, or something else?

**Comment by fromanifromage** [comment]
I might have the same error. First I see this message:
"balenaEtcher wants to make changes. Type your password to allow this."
Then I try to enter the correct password. I have tried alternating both the user and admin passwords; neither works. The program claims it will show a progress bar and it never shows.

**Comment by ldon13** [comment]
@thundron, After typing the password nothing happens. I don’t know what the reasoning behind switching to a custom prompt only asking for the password while the default MacOS prompt asks both for username and password. It hasn’t been a problem with the default in the previous versions.

**Comment by thundron** [comment]
@ldon13 Reason is macOS Catalina unfortunately 🤦‍♂ 
If you run with `sudo` does it work?
Can you paste here the output in the devtools console *after* closing the password dialogue? (`cmd + opt + i` to open it)

**Comment by JokerQyou** [comment]
When running in macOS Catalina 10.15.1, Etcher used to work properly, and a dialog like this would popup before actually flashing to SD card:
![image](https://user-images.githubusercontent.com/1465267/70861101-b3aef600-1f64-11ea-94d9-dd296295a3c6.png)

After upgrading to Catalina 10.15.2, Etcher changed to this popup:
![image](https://user-images.githubusercontent.com/1465267/70861123-d3deb500-1f64-11ea-931a-3ca54ca29950.png)

And whatever you type in this dialog does not work, even if the password is correct. If you click "OK", it will popup again; if you click "Cancel", well, it cancels the flash.

**Comment by lurch** [comment]
> I did not find related description in the changelog

I think #2939 is the relevant PR ? Which only appears in the changelog as https://github.com/balena-io/etcher/blob/master/CHANGELOG.md#v1561

**Comment by lurch** [comment]
AFAICT, this sounds like the problem I described here: https://github.com/balena-io/etcher/issues/3107#issuecomment-602047807

**Comment by JokerQyou** [comment]
> This comment says that even PrivilegedHelperTools (whatever they are) don't work in Catalina either.

I guess not. ApplePiBaker uses privileged helper tool, but it's working all the time. I installed it last year (you can see my comment above) and the last time I used it two weeks ago everything works fine. I've long been using Catalina (currently on 10.15.6)

**Comment by shawaj** [comment]
This should be fixed now in v1.5.112. @Decrypt0r @JokerQyou @fromanifromage could you update to the latest version and check if it now works for you?

**Comment by sjohnson-imi** [comment]
The issue is still occurring. I'm using v1.5.115 on Catalina. It only asks for a password (not an administrator login) and then silently kicks back to the "select target" decision. I tried repeating this thrice (and on to five times) to see if that would get by, but no change.

**Comment by sjohnson-imi** [comment]
Seems to stem from the change from asking for admin credentials to asking for user credentials and relying on sudoers to allow access.  Once I added the standard user account to the sudoers file, etcher was able to complete.

**Comment by MennoLabs** [comment]
I am using 1.5.121 on Kubuntu 21.04.
After selecting a target, a password prompt pops up and disappears before I can enter a password.
The application then stalls at "Starting...", without ever actually starting.

**Comment by DavidAmeba123** [comment]
Is there a default username and password for Etcher? I'm trying to download the setup but they are asking for a username and password before they allow me to download.

**Comment by mcraa** [comment]
@DavidAmeba123 the real etcher website is not asking you any password
Please have a look at #3724 and double-check if you are really on https://etcher.io.
When you start a flash with etcher it will ask you for an admin password to have all the rights for writing the target drive.

**Comment by lurch** [comment]
> double-check if you are really on https://etcher.io/

That auto-redirects to https://www.balena.io/etcher/ :wink:

**Comment by jdeibele** [comment]
I'm on Ventura Public Beta and having a similar problem to what [JokerQyou](https://github.com/JokerQyou) reported back in 2019.  It's worse in that I can't flash.

I run as a user without administrative privileges.   There is a different account with administrative privileges.   Normally, I need to type in the name and password of an account with administrative privileges.

When I try to flash an ISO, I get this:

<img width="417" alt="Screenshot 2022-07-22 at 09 03 01" src="https://user-images.githubusercontent.com/264802/180479259-90615eac-07b0-4a35-b8bf-dd74c00e93cb.png">

Note that it is not asking for the name of an administrative account.  On my computer, there is one account with administrative privileges but there could be 10.

After entering the password for the administrative account 3 times, I get this:
<img width="798" alt="Screenshot 2022-07-22 at 09 03 25" src="https://user-images.githubusercontent.com/264802/180479439-a1e35b3e-5ae4-4410-bb02-13fef3e9dcb1.png">

The "Flash!" button flickers but doesn't do anything.   I choose "Select Target" and repeat the cycle.

**Comment by kmbgit** [comment]
This works from a terminal (where "admin" is the name of a user with Administrator permission)...

su admin -c "sudo /Applications/balenaEtcher.app/Contents/MacOS/balenaEtcher"

Alternatively, download the Raspberry Pi Imager from https://www.raspberrypi.com/software/ - it manages to ask for an admin username/password so it must be possible.

**Comment by dfunckt** [comment]
Closing in favor of #3321
