### ISSUE TITLE
Unable to proceed past Flash from file

### ISSUE THREAD

**Issue by afurno-cisco** [balena-io/etcher#4234]
- **Etcher version:**  1.19.19, Type = local
- **Operating system and architecture:** Windows 10, AMD and Windows 11 Intel
- **Image flashed:** attempting to flash Ubuntu 22.04
- **What do you think should have happened:**
1. click "Flash from file"
2. select Ubuntu ISO from file explorer popup
3. should be able to select target
- **What happened:**
1. click "Flash from file"
2. select Ubuntu ISO from file explorer popup
3. Flash from file button greyed out, cannot select a target
![image](https://github.com/balena-io/etcher/assets/149194955/2ed4483f-cb9f-4eff-8db8-abb5144f3d06)
hovering over "select target" changes pointer to not-allowed
behavior is identical when running as administrator 
- **Do you see any meaningful error information in the DevTools?** 
```
Spawning unpriviledged sidecar on port 3434
3index.js:2 Starting...
index.js:2 C:\Users\afurno\AppData\Local\balena_etcher\app-1.19.19\resources\etcher-util.exe
index.js:2 etcher-4mqku7
index.js:2 Retrying to connect to child process in 1000... 1 / 10
index.js:2 etcher-4mqku7
index.js:2 Retrying to connect to child process in 1000... 2 / 10
index.js:2 etcher-4mqku7
index.js:2 CHILD READY
index.js:2 start heartbeat
index.js:2 CHILD LOG: Ready ...
index.js:2 CHILD LOG: Scan requested
```
these logs all come from startup, nothing is logged when I select Flash from file and select the iso

Downgrading to 1.18.11 resolved the issue

**Comment by marcenuc** [comment]
Same behaviour on Ubuntu 23.10 trying to flash ubuntu-24.04-desktop-amd64.iso.

After a few seconds, the following error is displayed:
Error opening source
Something went wrong while opening ubuntu-24.04-desktop-amd64.iso
Error: (0, h.requestMetadata) is not a function.

**Comment by afurno-cisco** [comment]
> Same behaviour on Ubuntu 23.10 trying to flash ubuntu-24.04-desktop-amd64.iso.
> 
> After a few seconds, the following error is displayed: Error opening source Something went wrong while opening ubuntu-24.04-desktop-amd64.iso Error: (0, h.requestMetadata) is not a function.

I never got an error, it just sat there for ~10 minutes until I closed the program

**Comment by andrejdaskalov** [comment]
I have the same error while trying to flash Ubuntu 24.04. 
I'm running Etcher on Windows 11

**Comment by SmArtKar** [comment]
Same here

**Comment by AimadMoustajil** [comment]
1. Verify the ISO File
Ensure the Ubuntu ISO file is not corrupted. You can verify the integrity of the ISO file by comparing its checksum with the one provided by the Ubuntu official website.

2. Run Etcher as Administrator
Running Etcher with administrative privileges can resolve permission-related issues. Right-click on the Etcher icon and select "Run as administrator".

3. Update Etcher
Ensure you are using the latest version of Etcher. Sometimes, bugs are fixed in newer versions, so updating might resolve the issue.

4. Check File Permissions
Ensure that the ISO file and the Etcher application have the appropriate read/write permissions.

5. Re-download the ISO
If the ISO file is corrupted, re-downloading it from the official Ubuntu website might solve the issue.

6. Disable Security Software
Sometimes, antivirus or other security software can interfere with Etcher. Temporarily disable any security software and try again.

7. Clear Etcher Cache
Etcher stores some data in cache that might cause issues. Clearing the cache might help.

On Windows, Etcher stores its cache in C:\Users\<Your-User-Name>\AppData\Roaming\etcher.
Delete the cache and try running Etcher again.
8. Try a Different USB Drive
The issue might be related to the USB drive you are using. Try using a different USB drive.

9. Reinstall Etcher
Uninstall and reinstall Etcher to ensure there are no corrupted files or settings.

10. Use an Alternative Tool
If Etcher continues to give you trouble, you can use an alternative tool to create a bootable USB. Some popular alternatives include:

Rufus
UNetbootin
Universal USB Installer
Step-by-Step Guide to Reinstall Etcher
Uninstall Etcher:

Go to Control Panel > Programs > Programs and Features.
Find Etcher in the list, right-click on it, and select Uninstall.
Delete Etcher Cache:

Navigate to C:\Users\<Your-User-Name>\AppData\Roaming.
Delete the etcher folder if it exists.
Download the Latest Version:

Go to the Etcher official website.
Download the latest version for Windows.
Install Etcher:

Run the downloaded installer and follow the on-screen instructions to install Etcher.
Run Etcher as Administrator:

After installation, right-click on the Etcher icon and select Run as administrator.
Creating a Bootable USB with Rufus
If you decide to use Rufus as an alternative, here’s how you can create a bootable USB:

Download Rufus:

Go to the [Rufus official website](https://rufus.ie/).
Download the latest version of Rufus.
Run Rufus:

No installation is needed, just run the Rufus executable.
Select USB Drive and ISO:

In the Rufus main window, select your USB drive.
Click on the SELECT button and choose the Ubuntu ISO file.
Start the Process:

Click START to begin the process of creating the bootable USB.
Follow any additional prompts.

**Comment by NotGabe001** [comment]
Same here. Windows 11, trying to flash Solus 4.5. Running as administrator and clearing cache did not help.

**Comment by intuser** [comment]
Same here. (Windows 11 Pro, newest Etcher.) Running as administrator doesn't help. Rufus: Uses doubleclick, Edge wouldn't even allow to download it without some security add-on. UNetbootin: usb isn't bootable.

**Comment by intuser** [comment]
I tested the result of the last advice and of UNetbootin on my working dual boot (Linux, Windows) machine. Selecting the usb drive to boot in both cases I end up with a grub prompt (actually two grub prompts). Something like "grub >".

**Comment by aethernet** [comment]
> Same behaviour on Ubuntu 23.10 trying to flash ubuntu-24.04-desktop-amd64.iso.
> 
> After a few seconds, the following error is displayed: Error opening source Something went wrong while opening ubuntu-24.04-desktop-amd64.iso Error: (0, h.requestMetadata) is not a function.

That's a different issue. Can you open another ticket ?

**Comment by aethernet** [comment]
Found the issue for windows... will be fixed in a couple minutes

**Comment by cngr** [comment]
I have the same isue in linux,but with etcher 1.18.12 work fine
![imagen](https://github.com/balena-io/etcher/assets/10997809/d67dc3f8-ecea-4bb3-a6b9-f83846a52444)

**Comment by DevEdoardoCorradetti** [comment]
On Windows 10 Home, Version 22H2, downgrading to balenaEtcher-Portable-1.18.11 from [this SourceForge link](https://sourceforge.net/projects/etcher.mirror/files/v1.18.11/balenaEtcher-Portable-1.18.11.exe/download) does not cause the same issue as downloading balenaEtcher-1.19.19.Setup from [the official Etcher website](https://etcher.balena.io/).

**Comment by aethernet** [comment]
Those two version 1.18 and 1.19 are completely different. The problem for windows is identified and a patch is under development.

**Comment by aethernet** [comment]
The linux issue is different tho and will need to be dealt in another ticket.

**Comment by aethernet** [comment]
The windows problem is fixed in 1.19.21 (waiting for CI to finish the release, will take a minute or so).
The linux/ubuntu problem will require a deeper exploration

**Comment by intuser** [comment]
I installed the new version, but the problem persists. Again, running as administrator doesn't help. Also downloading the iso again didn't help. (ubuntu-24.04-desktop-amd64.iso)

**Comment by NotGabe001** [comment]
Works for me now, ISO boots as well

**Comment by Sensang** [comment]
Same issue on windows 10.. I've tried using an image from a URL instead and now it just takes forever to load.

**Comment by KartikeyaWalia** [comment]
I think there are still issues with etcher working with Win11. I was trying for the past 30 mins. Then used win32diskimager and it worked fine.

**Comment by dye46** [comment]
ubuntu-24.04-desktop-amd64.iso yields the same hang (just after file selection) 1.19.21 version.  fresh-ish win10 Pro install.

iso image latest Desktop version from Ubuntu.

md5 checksum:
md5sum Downloads/ubuntu-24.04-desktop-amd64*
3b7c9731cd61b718a9163a0cbab27512 *Downloads/ubuntu-24.04-desktop-amd64(1).iso
3b7c9731cd61b718a9163a0cbab27512 *Downloads/ubuntu-24.04-desktop-amd64.iso

**Comment by marksholcomb** [comment]
Windows 11 ... I have experienced the issue where etcher is unable to write to my USB drive.
My USB (2.0?) drive was plugged into an expander.   I moved the USB drive to a port directly on the computer (3.0?) and it works!  Maybe this is explained in this thread somewhere.

**Comment by AlejandroElingeMecatronico** [comment]
Hi. I've had the same problem and I resolved this with a simple step: **I ran the etcher how administrator**. With I hope you could flash the iso!!!!

**Comment by RobTangle** [comment]
I had the same problem in Windows 10 trying to use the Ubuntu 24.06 iso. But running balenaEtcher-1.19.21.Setup file as administrator solved the issue!

**Comment by mdilena** [comment]
I was getting this error on Ubuntu 22.04 and, similarly to what suddenly started happening with Vivaldi web browser, I ran `./balena-etcher --disable-gpu` and it worked :shrug:

**Comment by ECiurleo** [comment]
Still having this issue with 1.19.22 installed on fedora 40 via the RPM.

Tried --disable-gpu, running as sudo --no--sandbox and continue to get the same error when trying to load Win11_23H2_EnglishInternational_x64v2.iso (official download)

**Comment by jhebb-hass** [comment]
Also having this issue on Windows 10 22H2

**Comment by RobTangle** [comment]
I kept having problems with Balena. My solution was to just use Rufus instead. It worked perfectly with Rufus

**Comment by renWebGit** [comment]
Same problem here with 1.19.25 running on Windows 10 22H2 and selecting ubuntu-24.04.1-desktop-amd64

**Comment by shxwheen** [comment]
> Same behaviour on Ubuntu 23.10 trying to flash ubuntu-24.04-desktop-amd64.iso.
> 
> After a few seconds, the following error is displayed: Error opening source Something went wrong while opening ubuntu-24.04-desktop-amd64.iso Error: (0, h.requestMetadata) is not a function.

I ran it as administrator and it got rid of this problem

**Comment by davidtomlinjr** [comment]
Still an issue with the latest build of Windows 11 attempting to flash ubuntu 24.10.

**Comment by UltraCenterHQ** [comment]
I had the same issue, even after I ran it as admin. till I ran the installer itself as admin. But then I tested it again without that and the gray freeze bug didn't happen again. Maybe it's actually because I formatted my flash drive as fat32?

this feels like the Thursday print bug lmao

**Comment by purewm** [comment]
MAC SOLUTION:

I had the same issue, using:

- Balena Etcher 1.19.25
- Lexar 32GB USB3 drive
- lmde-6-cinnamon-64bit.iso
- M1 Mac

and I kept running into the same error (saying something was wrong with the iso image) but then when I reformatted the USB drive as MS-DOS and GUID Partition, it worked without an issue on Balena, and super quickly too. 

Hopefully that is the solution for others here.

**Comment by frizzz** [comment]
<img width="1017" height="653" alt="Image" src="https://github.com/user-attachments/assets/eb7d29f4-fed9-47da-a69a-2b5ecfa7664c" />

still the error, version 2.1.2 using W11.

WHY IS NOT POSSIBLE TO DOWNLOAD OLD VERSION?????

**Comment by cbatson** [comment]
> The linux/ubuntu problem will require a deeper exploration

Is there another issue to track this?

Experiencing this on version 2.1.4, macOS Sequoia, Apple silicon. Some messaging or other feedback when something goes wrong would be great.

**Comment by Gurtensten-Nirel** [comment]
I had this issue when trying to burn a Pop_OS! ISO onto a USB on Windows 11.

If anyone is still having this issue of freezing after "Flash from file", you can try downloading version number 1.18.11 (from 2023-06-17), It fixed the problem for me.
For some reason, some later versions freeze, but this one works.

You can find it on their official github etcher realeases page:
https://github.com/balena-io/etcher/releases

P.S.
Nothing else worked, I tried running it as administrator, tried it after it was burnt with another ISO, tried formatting the USB and then burn it, tried moving folder locations, tried uninstalling and installing the version from github and a few more things, but this was the only fix.

Hope this helps someone :)

**Comment by streithausen** [comment]
I see this when an AD blocker is installed.

@frizzz 
Go to github and select an older version, like 1.18.11.
This works,
